import { chromium } from 'playwright-core';
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser = await chromium.launch({ executablePath: CHROME, headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
page.on('requestfailed', (r) => errors.push('REQFAIL ' + r.url()));
await page.goto('https://mcshera.github.io/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
const fonts = await page.evaluate(() => Array.from(document.fonts).filter(f => f.status === 'loaded').map(f => f.family).filter((v,i,a)=>a.indexOf(v)===i));
await page.screenshot({ path: '.scratch/scenes/live-home.png' });
await page.mouse.wheel(0, 700); await page.waitForTimeout(1800);
await page.screenshot({ path: '.scratch/scenes/live-plate.png' });
await page.goto('https://mcshera.github.io/work/skyweaver/', { waitUntil: 'networkidle' }); await page.waitForTimeout(1500);
await page.mouse.wheel(0, 600); await page.waitForTimeout(2500);
await page.screenshot({ path: '.scratch/scenes/live-sky.png' });
console.log(JSON.stringify({ fonts, errors }));
await browser.close();
