import { chromium } from 'playwright-core';
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser = await chromium.launch({ executablePath: CHROME, headless: true });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
await page.goto('http://127.0.0.1:8089/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2800);
await page.screenshot({ path: '.scratch/scenes/mob-hero.png' });
await page.tap('[data-menu-toggle]');
await page.waitForTimeout(1000);
await page.screenshot({ path: '.scratch/scenes/mob-menu.png' });
const menuState = await page.evaluate(() => ({ inert: document.querySelector('[data-menu]').hasAttribute('inert'), open: document.querySelector('[data-menu]').classList.contains('is-open'), expanded: document.querySelector('[data-menu-toggle]').getAttribute('aria-expanded') }));
await page.tap('[data-menu-link][href="/#work"]');
await page.waitForTimeout(2200);
await page.screenshot({ path: '.scratch/scenes/mob-work.png' });
const after = await page.evaluate(() => ({ y: Math.round(window.scrollY), theme: document.documentElement.getAttribute('data-theme'), menuOpen: document.querySelector('[data-menu]').classList.contains('is-open') }));
console.log(JSON.stringify({ menuState, after, errors }));
await browser.close();
